import {STORAGE_KEY,paintFields,loadDrafts,saveDrafts,findColor,compileScheme} from './scheme-store.js';
let drafts=[],catalog=[],current='A',dirty=false,storageError=false;const form=document.getElementById('scheme-form'),status=document.getElementById('save-status');
function message(text,error=false){status.textContent=text;status.style.color=error?'#a02c20':'#275e45';}
function tabs(){const nav=document.getElementById('scheme-tabs');nav.replaceChildren();for(const s of drafts){const b=document.createElement('button');b.type='button';b.setAttribute('aria-current',String(s.id===current));b.textContent=s.name;const small=document.createElement('small');small.textContent=compileScheme(s,catalog)?'Ready':'Draft';b.append(small);b.onclick=()=>{if(dirty&&!save())return;current=s.id;render();};nav.append(b);}}
function hint(key){const input=document.getElementById('paint-'+key),h=document.getElementById('hint-'+key),c=findColor(input.value,catalog);h.replaceChildren();input.setAttribute('aria-invalid',String(!!input.value.trim()&&!c));if(c){const sw=document.createElement('i');sw.style.background=c.hex;h.append(sw,document.createTextNode(c.code+' '+c.name+' · '+c.hex));}else h.textContent=input.value.trim()?'Color not found. Choose a listed SW color.':'Type a name or SW number.';return c;}
function render(){tabs();const s=drafts.find(s=>s.id===current);document.getElementById('scheme-title').textContent=s.name;const fields=document.getElementById('paint-fields');fields.replaceChildren();for(const [key,label]of Object.entries(paintFields)){const row=document.createElement('div');row.className='paint-field';const l=document.createElement('label');l.htmlFor='paint-'+key;l.textContent=label;const input=document.createElement('input');input.id='paint-'+key;input.value=s.paints[key];input.setAttribute('list','sw-catalog');input.setAttribute('aria-describedby','hint-'+key);input.placeholder='e.g. SW 7005 or Pure White';input.autocomplete='off';const h=document.createElement('p');h.className='paint-hint';h.id='hint-'+key;row.append(l,input,h);fields.append(row);input.oninput=()=>{dirty=true;hint(key);message('Unsaved changes.');};input.onblur=()=>{const c=hint(key);if(c)input.value=c.code+' '+c.name;};hint(key);}document.getElementById('garage-default').value=s.garageMatch;document.getElementById('shutter-default').value=s.shutterMatch;dirty=false;message('');}
function collect(){return {...drafts.find(s=>s.id===current),paints:Object.fromEntries(Object.keys(paintFields).map(k=>{const value=document.getElementById('paint-'+k).value.trim(),c=findColor(value,catalog);return [k,c?c.code+' '+c.name:value];})),garageMatch:document.getElementById('garage-default').value,shutterMatch:document.getElementById('shutter-default').value};}
function save(){if(storageError){message('Browser storage is unavailable. Changes have not been saved.',true);return false;}const draft=collect();for(const [key,value]of Object.entries(draft.paints)){if(value&&!findColor(value,catalog)){message('Please correct '+paintFields[key]+' or leave it blank to save a draft.',true);document.getElementById('paint-'+key).focus();return false;}}const next=drafts.map(s=>s.id===current?draft:s);try{saveDrafts(next);drafts=next;dirty=false;tabs();message(compileScheme(draft,catalog)?draft.name+' saved and ready to preview.':draft.name+' saved as a draft. Fill all eight paint fields to enable it in the preview.');return true;}catch{message('Your browser could not save these changes. Keep this page open and try again.',true);return false;}}
form.onsubmit=e=>{e.preventDefault();save();};for(const id of ['garage-default','shutter-default'])document.getElementById(id).onchange=()=>{dirty=true;message('Unsaved changes.');};
document.getElementById('export').onclick=()=>{if(dirty&&!save())return;const blob=new Blob([JSON.stringify({version:1,schemes:drafts},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='exterior-schemes-A-L.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Exported all twelve schemes.');};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_saved_color_schemes',description:'Read the twelve saved browser-local scheme drafts and their Sherwin-Williams colors for review or incorporation into the final product. Unsaved form edits are excluded.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({version:1,schemes:loadDrafts()})})).catch(()=>{});}catch{}}
fetch('sw-colors.json').then(r=>{if(!r.ok)throw Error('Catalog');return r.json();}).then(data=>{catalog=data;try{drafts=loadDrafts();}catch{storageError=true;throw Error('Storage');}const list=document.getElementById('sw-catalog');for(const c of catalog){const o=document.createElement('option');o.value=c.code+' '+c.name;list.append(o);}render();}).catch(e=>{message(e.message==='Storage'?'Saved schemes could not be read. No existing data has been overwritten.':'The color catalog could not load. Please refresh.',true);form.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);});
