import {createSelectionImage} from './export-preview.js';
import {validateScheme,resolveColors,garageChoices,shutterChoices} from './scheme-model.js';
import {STORAGE_KEY,loadDrafts,compileScheme} from './scheme-store.js';
const labels={siding1:'Primary Siding',siding2:'Secondary Siding',trim:'Trim',fascia:'Fascia',door:'Entry Door',garage:'Garage Door',shutters:'Shutters'};
const base={siding1:'#FFFFFF',siding2:'#FFFFFF',trim:'#FFFFFF',fascia:'#FFFFFF',door:'#FFFFFF'};
let schemes=[],drafts=[],catalog=[],active=null,doorIndex=0,garageMatch='siding1',shutterMatch='door',colors={};
const canvas=document.getElementById('house'),ctx=canvas.getContext('2d'),photo=new Image(),landscaping=new Image(),controls=document.getElementById('controls');let ready=false,surfaces={};
function selectControl(title,id,choices,value,change){const box=document.createElement('div');box.className='choice';const label=document.createElement('label');label.htmlFor=id;label.textContent=title;const select=document.createElement('select');select.id=id;for(const [key,name]of choices){const o=document.createElement('option');o.value=key;o.textContent=name;select.append(o);}select.value=value;select.onchange=()=>change(select.value);box.append(label,select);controls.append(box);return select;}
function buildControls(){controls.replaceChildren();
 const select=selectControl('Color scheme','scheme',drafts.length?drafts.map(s=>[s.id,s.name+(schemes.some(r=>r.id===s.id)?'':' — not configured')]):[['','Loading schemes…']],active?.id||drafts[0]?.id||'',chooseScheme);select.disabled=!schemes.length;for(const o of select.options)o.disabled=!schemes.some(s=>s.id===o.value);
 if(!active){const p=document.createElement('p');p.className='pending';p.textContent='Set up your colors for Schemes A–L on the admin page. Completed schemes will appear here.';const a=document.createElement('a');a.href='admin.html';a.textContent='Open Scheme Admin';a.className='admin-link';controls.append(p,a);update();return;}
 for(const key of ['siding1','siding2','trim','fascia']){const row=document.createElement('div');row.className='control';row.innerHTML=`<input type="color" id="${key}" aria-label="${labels[key]} color"><label for="${key}">${labels[key]}</label><output id="${key}-hex"></output>`;const input=row.querySelector('input');input.disabled=!!active;input.oninput=()=>{base[key]=input.value;update();};controls.append(row);}
 if(active){selectControl('Entry door','door-option',active.doors.map((d,i)=>[String(i),d.name]),String(doorIndex),i=>{doorIndex=Number(i);base.door=active.doors[doorIndex].color;update();});}else{const row=document.createElement('div');row.className='control';row.innerHTML='<input type="color" id="door" aria-label="Entry door color"><label for="door">Entry door</label><output id="door-hex"></output>';row.querySelector('input').oninput=e=>{base.door=e.target.value;update();};controls.append(row);}
 selectControl('Garage door matches','garage-match',garageChoices.map(k=>[k,labels[k]]),garageMatch,v=>{garageMatch=v;update();});
 selectControl('Shutters match','shutters-match',shutterChoices.map(k=>[k,labels[k]]),shutterMatch,v=>{shutterMatch=v;update();});decorateControls();update();
}
function chooseScheme(id){const s=schemes.find(s=>s.id===id);if(!s)throw Error('Unknown scheme.');active=s;doorIndex=0;garageMatch=s.garageMatch||'siding1';shutterMatch=s.shutterMatch||'door';for(const k of ['siding1','siding2','trim','fascia'])base[k]=s[k];base.door=s.doors[0].color;buildControls();}
function decorateControls(){
 if(!active||!document.body.classList.contains('customer'))return;
 document.getElementById('preview-scheme').textContent=active.name;
 const schemeSelect=document.getElementById('scheme');schemeSelect.parentElement.classList.add('visually-hidden');
 const section=document.createElement('section');section.className='scheme-section';section.innerHTML='<h3 class="step-title"><b>1</b> Choose your palette</h3><div class="scheme-grid"></div>';
 for(const scheme of schemes){const b=document.createElement('button');b.type='button';b.className='scheme-card';b.setAttribute('aria-label',scheme.name);b.setAttribute('aria-pressed',String(scheme.id===active.id));b.innerHTML='<span class="mini-palette">'+['siding1','siding2','trim','fascia'].map(k=>'<i style="background:'+scheme[k]+'"></i>').join('')+'</span>'+scheme.id;b.onclick=()=>{chooseScheme(scheme.id);controls.querySelector('[aria-label="'+scheme.name+'"]').focus({preventScroll:true});};section.lastElementChild.append(b);}
 const fixed=document.createElement('div');fixed.className='fixed-palette';controls.querySelectorAll('.control').forEach(el=>fixed.append(el));section.append(fixed);controls.prepend(section);
 const doorSelect=document.getElementById('door-option');doorSelect.parentElement.classList.add('visually-hidden');const doors=document.createElement('section');doors.innerHTML='<h3 class="step-title"><b>2</b> Pick your entry door</h3><div class="door-grid"></div>';
 active.doors.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.className='door-card';b.setAttribute('aria-pressed',String(i===doorIndex));b.innerHTML='<i style="background:'+d.color+'"></i><span><small>'+d.name.slice(0,6)+'</small>'+d.name.slice(7)+'</span>';b.onclick=()=>{doorIndex=i;base.door=d.color;doorSelect.value=String(i);update();};doors.lastElementChild.append(b);});controls.insertBefore(doors,doorSelect.parentElement);
 const heading=document.createElement('h3');heading.className='step-title';heading.innerHTML='<b>3</b> Coordinate the details';controls.insertBefore(heading,document.getElementById('garage-match').parentElement);
}
function update(){document.querySelectorAll('.door-card').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===doorIndex)));colors=resolveColors(base,garageMatch,shutterMatch);for(const k of Object.keys(base)){const input=document.getElementById(k);if(input)input.value=base[k];const text=document.getElementById(k+'-hex');if(text)text.textContent=active?.refs?.[k] ? active.refs[k].code+' '+active.refs[k].name : base[k].toUpperCase();}document.getElementById('legend').innerHTML=Object.entries(labels).map(([k,v])=>`<span><i style="background:${colors[k]}"></i>${v}</span>`).join('');draw();return {...colors};}
function polygon(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
function draw(){if(!ready)return;ctx.globalCompositeOperation='source-over';ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.scale(canvas.width/1536,canvas.height/1024);for(const [key,polys]of Object.entries(surfaces))for(const points of polys)polygon(points,colors[key]||'#FFFFFF');ctx.restore();ctx.globalCompositeOperation='multiply';ctx.drawImage(photo,0,0,canvas.width,canvas.height);ctx.globalCompositeOperation='source-over';if(landscaping.complete && landscaping.naturalWidth){ctx.save();ctx.scale(canvas.width/1536,canvas.height/1024);ctx.drawImage(landscaping,842,586,575,192);ctx.restore();}}
landscaping.onload=()=>draw();landscaping.src='landscaping.png';
photo.onload=()=>{canvas.width=photo.naturalWidth;canvas.height=photo.naturalHeight;ready=true;document.getElementById('loading').hidden=true;draw();};photo.onerror=()=>document.getElementById('loading').textContent='The rendering could not load. Please refresh.';
document.getElementById('reset').onclick=()=>{garageMatch='siding1';shutterMatch='door';if(active)chooseScheme(active.id);else{for(const k in base)base[k]='#FFFFFF';buildControls();}};
buildControls();
function refreshSchemes(){drafts=loadDrafts();schemes=drafts.map(d=>compileScheme(d,catalog)).filter(Boolean).map(validateScheme);const selected=schemes.find(s=>s.id===active?.id)||schemes[0];if(selected)chooseScheme(selected.id);else{active=null;for(const k in base)base[k]='#FFFFFF';buildControls();}}
Promise.all(['surfaces.json','sw-colors.json'].map(path=>fetch(path).then(r=>{if(!r.ok)throw Error('Load failed');return r.json();}))).then(([m,c])=>{surfaces=m;catalog=c;refreshSchemes();photo.src='rendering-clean.png';}).catch(()=>document.getElementById('loading').textContent='The preview or saved schemes could not load. Please refresh.');
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){try{refreshSchemes();}catch{document.getElementById('loading').hidden=false;document.getElementById('loading').textContent='Saved schemes could not be read.';}}});
function configure(input){if(!input||typeof input!=='object')throw Error('Invalid input.');if(input.scheme!==undefined&&!schemes.some(s=>s.id===input.scheme))throw Error('Unknown scheme.');const target=input.scheme?schemes.find(s=>s.id===input.scheme):active;if(input.doorOption!==undefined&&(!target||!Number.isInteger(input.doorOption)||input.doorOption<0||input.doorOption>3))throw Error('Choose door option 0 through 3 within a scheme.');if(input.garageMatch!==undefined&&!garageChoices.includes(input.garageMatch))throw Error('Invalid garage match.');if(input.shutterMatch!==undefined&&!shutterChoices.includes(input.shutterMatch))throw Error('Invalid shutter match.');if(input.previewColors){if(target)throw Error('Scheme colors are fixed.');for(const [k,v]of Object.entries(input.previewColors))if(!(k in base)||!/^#[0-9a-f]{6}$/i.test(v))throw Error('Invalid preview color.');}if(input.scheme)chooseScheme(input.scheme);if(input.doorOption!==undefined){doorIndex=input.doorOption;base.door=active.doors[doorIndex].color;}if(input.garageMatch)garageMatch=input.garageMatch;if(input.shutterMatch)shutterMatch=input.shutterMatch;if(input.previewColors)Object.assign(base,input.previewColors);buildControls();return {scheme:active?.id||null,doorOption:active?doorIndex:null,garageMatch,shutterMatch,colors};}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_exterior_scheme',description:'Choose a supplied scheme, one of its four door options, and matching rules. Until scheme palettes are supplied, previewColors can set base colors.',inputSchema:{type:'object',properties:{scheme:{type:'string'},doorOption:{type:'integer',minimum:0,maximum:3},garageMatch:{type:'string',enum:garageChoices},shutterMatch:{type:'string',enum:shutterChoices},previewColors:{type:'object',properties:Object.fromEntries(Object.keys(base).map(k=>[k,{type:'string',pattern:'^#[0-9a-fA-F]{6}$'}])),additionalProperties:false}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:configure})).catch(()=>{});}catch{}}



document.getElementById('save-preview')?.addEventListener('click',async()=>{
 if(!ready||!active)return;
 const button=document.getElementById('save-preview');button.disabled=true;
 try{
  await landscaping.decode().catch(()=>{});draw();
  const paintName=k=>{if(k==='door')return active.doors[doorIndex].name;if(k==='garage')return paintName(garageMatch);if(k==='shutters')return paintName(shutterMatch);const r=active.refs?.[k];return r?r.code+' '+r.name:colors[k].toUpperCase();};
  const sheet=createSelectionImage(canvas,{scheme:active.name,rows:Object.entries(labels).map(([key,label])=>({label,color:colors[key],paint:paintName(key)}))});
  const blob=await new Promise(resolve=>sheet.toBlob(resolve,'image/png'));if(!blob)throw Error('Image could not be saved.');
  const url=URL.createObjectURL(blob),a=document.createElement('a');a.download='KB-Home-'+active.name.replaceAll(' ','-')+'-Selections.png';a.href=url;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
 }finally{button.disabled=false;}
});
